# Scan outdoor MoP maps for stacked duplicate creature spawns.
# Clusters spawns by map + entry + rounded position; keeps the SFDB baseline guid when present.
#
# Usage:
#   .\scan_duplicate_spawns.ps1 -Database world -VendorOnly
#   .\scan_duplicate_spawns.ps1 -Database world -AllNpcs -ApplyToDatabase world_dedup_test
#   .\scan_duplicate_spawns.ps1 -Database world -VendorOnly -WriteWorldUpdate

param(
    [string]$Database = 'world',
    [string]$BaselineDatabase = 'world_sfdb',
    [int[]]$Maps = @(870, 860, 859, 861, 1064, 1050, 1098, 1135, 1004),
    [switch]$VendorOnly,
    [switch]$AllNpcs,
    [string]$ApplyToDatabase,
    [switch]$WriteWorldUpdate,
    [switch]$DryRun
)

if (-not $VendorOnly -and -not $AllNpcs) {
    $VendorOnly = $true
}

. (Join-Path $PSScriptRoot 'config.ps1')
$cfg = $script:DbPortConfig
$env:MYSQL_PWD = $cfg.Password

$outDir = Join-Path $PSScriptRoot 'output'
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$mapList = ($Maps | ForEach-Object { [string]$_ }) -join ','
$scope = if ($VendorOnly) { 'vendor' } else { 'all_npc' }
$reportCsv = Join-Path $outDir ("duplicate_spawn_removals_{0}.csv" -f $scope)
$sqlFile = Join-Path $outDir ("duplicate_spawn_removals_{0}.sql" -f $scope)

$vendorFilterInner = @"
AND (
    (ct2.npcflag & 128)
    OR EXISTS (SELECT 1 FROM npc_vendor nv WHERE nv.entry = c2.id)
)
"@

$vendorFilterOuter = @"
AND (
    (ct.npcflag & 128)
    OR EXISTS (SELECT 1 FROM npc_vendor nv WHERE nv.entry = c.id)
)
"@

$filterSqlInner = if ($VendorOnly) { $vendorFilterInner } else { '' }
$filterSqlOuter = if ($VendorOnly) { $vendorFilterOuter } else { '' }

$deleteQuery = @"
SELECT
    c.map,
    ct.name,
    c.guid      AS delete_guid,
    k.keep_guid,
    c.id        AS entry,
    ROUND(c.position_x, 2) AS x,
    ROUND(c.position_y, 2) AS y,
    ROUND(c.position_z, 2) AS z,
    k.cluster_size,
    IF(b.guid IS NOT NULL, 1, 0) AS delete_in_baseline,
    IF(bk.guid IS NOT NULL, 1, 0) AS keep_in_baseline
FROM creature c
INNER JOIN creature_template ct ON ct.entry = c.id
INNER JOIN (
    SELECT
        c2.map,
        c2.id,
        ROUND(c2.position_x, 1) AS bx,
        ROUND(c2.position_y, 1) AS pos_y,
        ROUND(c2.position_z, 1) AS bz,
        COALESCE(
            MIN(CASE WHEN c2.guid >= 8000000 THEN c2.guid END),
            MIN(CASE WHEN bs.guid IS NOT NULL THEN c2.guid END),
            MIN(c2.guid)
        ) AS keep_guid,
        COUNT(*) AS cluster_size
    FROM creature c2
    INNER JOIN creature_template ct2 ON ct2.entry = c2.id
    LEFT JOIN ``$BaselineDatabase``.creature bs ON bs.guid = c2.guid
    WHERE c2.map IN ($mapList)
    $filterSqlInner
    GROUP BY c2.map, c2.id, bx, pos_y, bz
    HAVING COUNT(*) > 1
) k ON  k.map = c.map
   AND k.id = c.id
   AND ROUND(c.position_x, 1) = k.bx
   AND ROUND(c.position_y, 1) = k.pos_y
   AND ROUND(c.position_z, 1) = k.bz
   AND c.guid <> k.keep_guid
LEFT JOIN ``$BaselineDatabase``.creature b ON b.guid = c.guid
LEFT JOIN ``$BaselineDatabase``.creature bk ON bk.guid = k.keep_guid
WHERE c.map IN ($mapList)
$filterSqlOuter
ORDER BY c.map, ct.name, c.guid;
"@

Write-Host "Scanning '$Database' (baseline: $BaselineDatabase, scope: $scope, maps: $mapList)"

$lines = Invoke-DbPortQuery -Query $deleteQuery -Database $Database
if (-not $lines) {
    Write-Host "No duplicate clusters found."
    exit 0
}

$rows = foreach ($line in $lines) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    $p = $line -split "`t"
    if ($p.Count -lt 11) { continue }
    [pscustomobject]@{
        Map              = $p[0]
        Name             = $p[1]
        DeleteGuid       = $p[2]
        KeepGuid         = $p[3]
        Entry            = $p[4]
        X                = $p[5]
        Y                = $p[6]
        Z                = $p[7]
        ClusterSize      = $p[8]
        DeleteInBaseline = $p[9]
        KeepInBaseline   = $p[10]
    }
}

$rows | Export-Csv -Path $reportCsv -NoTypeInformation -Encoding UTF8

$guids = $rows | ForEach-Object { $_.DeleteGuid } | Sort-Object { [uint64]$_ }
Write-Host ("Found {0} spawns to remove across {1} clusters." -f $guids.Count, ($rows | Select-Object -Property Map,Name,X,Y,Z -Unique).Count)

$baselineDeletes = @($rows | Where-Object { $_.DeleteInBaseline -eq '1' })
if ($baselineDeletes.Count -gt 0) {
    Write-Host ("WARNING: {0} deletes are guids that exist in baseline (usually SFDB had stacked copies too)." -f $baselineDeletes.Count)
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("-- Duplicate spawn cleanup ($scope)")
[void]$sb.AppendLine("-- Generated by tools/db-port/scan_duplicate_spawns.ps1")
[void]$sb.AppendLine("-- Database: $Database | Baseline: $BaselineDatabase | Maps: $mapList")
[void]$sb.AppendLine("DELETE FROM ``creature`` WHERE ``guid`` IN (")

for ($i = 0; $i -lt $guids.Count; $i += 100) {
    $end = [Math]::Min($i + 99, $guids.Count - 1)
    $chunk = $guids[$i..$end]
    $suffix = if ($end -lt $guids.Count - 1) { ',' } else { '' }
    [void]$sb.AppendLine('    ' + (($chunk | ForEach-Object { [string]$_ }) -join ', ') + $suffix)
}
[void]$sb.AppendLine(');')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($sqlFile, $sb.ToString(), $utf8NoBom)

Write-Host "Wrote report: $reportCsv"
Write-Host "Wrote SQL:    $sqlFile"

$rows | Group-Object Map | Sort-Object Name | ForEach-Object {
    Write-Host ("  map {0}: {1} removals" -f $_.Name, $_.Count)
}

if ($WriteWorldUpdate) {
    Write-Warning "Use generate_spawn_dedup_update.ps1 -OutputFile YYYY-MM-DD_world_XX.sql for consolidated world updates."
}

if ($ApplyToDatabase) {
    if ($DryRun) {
        Write-Host "DryRun: would apply $($guids.Count) deletes to '$ApplyToDatabase'."
    } else {
        Write-Host "Applying deletes to '$ApplyToDatabase'..."
        Invoke-DbPortSqlFile -SqlFile $sqlFile -Database $ApplyToDatabase | Out-Null
        Write-Host "Done."
    }
}
