-- spell_script_names gap-fill for unbound C++ spell scripts

INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`)
SELECT v.`spell_id`, v.`ScriptName`
FROM (
    SELECT 89832 AS `spell_id`, 'spell_dk_death_strike_enabler' AS `ScriptName`
    UNION ALL SELECT 48792, 'spell_dk_icebound_fortitude'
    UNION ALL SELECT 59754, 'spell_dk_rune_tap_party'
    UNION ALL SELECT 50421, 'spell_dk_scent_of_blood'
    UNION ALL SELECT 54846, 'spell_dru_glyph_of_starfire'
    UNION ALL SELECT 54845, 'spell_dru_glyph_of_starfire_proc'
    UNION ALL SELECT -16972, 'spell_dru_predatory_strikes'
    UNION ALL SELECT -78892, 'spell_dru_stampede'
    UNION ALL SELECT 123933, 'spell_gen_override_display_power'
    UNION ALL SELECT 145627, 'spell_gen_override_display_power'
    UNION ALL SELECT 145628, 'spell_gen_override_display_power'
    UNION ALL SELECT 145044, 'spell_gen_override_display_power'
    UNION ALL SELECT 82926, 'spell_hun_fire'
    UNION ALL SELECT -19464, 'spell_hun_improved_serpent_sting'
    UNION ALL SELECT 53412, 'spell_hun_invigoration'
    UNION ALL SELECT 82925, 'spell_hun_ready_set_aim'
    UNION ALL SELECT 56641, 'spell_hun_steady_shot'
    UNION ALL SELECT -34497, 'spell_hun_thrill_of_the_hunt'
    UNION ALL SELECT 12880, 'spell_mastery_unshackled_fury'
    UNION ALL SELECT 17, 'spell_mastery_shield_discipline'
    UNION ALL SELECT 123258, 'spell_mastery_shield_discipline'
    UNION ALL SELECT 114908, 'spell_mastery_shield_discipline'
    UNION ALL SELECT 114214, 'spell_mastery_shield_discipline'
    UNION ALL SELECT 47753, 'spell_mastery_shield_discipline'
    UNION ALL SELECT 100780, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 108557, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 115698, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 115687, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 115693, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 115695, 'spell_mastery_combo_breaker'
    UNION ALL SELECT 45470, 'spell_mastery_blood_shield'
    UNION ALL SELECT 133, 'spell_mastery_ignite'
    UNION ALL SELECT 44614, 'spell_mastery_ignite'
    UNION ALL SELECT 108853, 'spell_mastery_ignite'
    UNION ALL SELECT 2948, 'spell_mastery_ignite'
    UNION ALL SELECT 11366, 'spell_mastery_ignite'
    UNION ALL SELECT 35395, 'spell_mastery_hand_of_light'
    UNION ALL SELECT 53595, 'spell_mastery_hand_of_light'
    UNION ALL SELECT 24275, 'spell_mastery_hand_of_light'
    UNION ALL SELECT 85256, 'spell_mastery_hand_of_light'
    UNION ALL SELECT 53385, 'spell_mastery_hand_of_light'
    UNION ALL SELECT 403, 'spell_mastery_elemental_overload'
    UNION ALL SELECT 421, 'spell_mastery_elemental_overload'
    UNION ALL SELECT 51505, 'spell_mastery_elemental_overload'
    UNION ALL SELECT 117014, 'spell_mastery_elemental_overload'
    UNION ALL SELECT 127722, 'spell_monk_serpents_zeal'
    UNION ALL SELECT 125893, 'spell_monk_glyph_of_zen_flight'
    UNION ALL SELECT 117952, 'spell_monk_crackling_jade_lightning'
    UNION ALL SELECT 123408, 'spell_monk_spinning_fire_blossom_damage'
    UNION ALL SELECT 107270, 'spell_monk_teachings_of_the_monastery'
    UNION ALL SELECT 115294, 'spell_monk_glyph_of_mana_tea'
    UNION ALL SELECT 123766, 'spell_monk_mana_tea_stacks'
    UNION ALL SELECT 124081, 'spell_monk_zen_sphere_hot'
    UNION ALL SELECT 123986, 'spell_monk_chi_burst'
    UNION ALL SELECT 31821, 'spell_pal_aura_mastery'
    UNION ALL SELECT 64364, 'spell_pal_aura_mastery_immune'
    UNION ALL SELECT 37705, 'spell_pal_item_healing_discount'
    UNION ALL SELECT 37594, 'spell_pri_item_greater_heal_refund'
    UNION ALL SELECT 15290, 'spell_pri_vampiric_embrace_target'
    UNION ALL SELECT -51625, 'spell_rog_crippling_poison'
    UNION ALL SELECT 52041, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52046, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52047, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52048, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52049, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52050, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52059, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52060, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 52061, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 58759, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 58760, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 58761, 'spell_sha_healing_stream_totem'
    UNION ALL SELECT 23551, 'spell_sha_item_lightning_shield'
    UNION ALL SELECT 23552, 'spell_sha_item_lightning_shield_trigger'
    UNION ALL SELECT 23572, 'spell_sha_item_mana_surge'
    UNION ALL SELECT 16191, 'spell_sha_mana_tide_totem'
    UNION ALL SELECT -30881, 'spell_sha_nature_guardian'
    UNION ALL SELECT 82984, 'spell_sha_telluric_currents'
    UNION ALL SELECT 82988, 'spell_sha_telluric_currents'
    UNION ALL SELECT 51490, 'spell_sha_thunderstorm'
    UNION ALL SELECT 6262, 'spell_warl_healthstone_heal'
    UNION ALL SELECT 92795, 'spell_warl_soul_swap_dot_marker'
    UNION ALL SELECT 86211, 'spell_warl_soul_swap_override'
    UNION ALL SELECT 12809, 'spell_warr_concussion_blow'
    UNION ALL SELECT 59725, 'spell_warr_improved_spell_reflection'
    UNION ALL SELECT 94009, 'spell_warr_rend'
    UNION ALL SELECT 20230, 'spell_warr_retaliation'
    UNION ALL SELECT 32216, 'spell_warr_victorious'
    UNION ALL SELECT 82368, 'spell_warr_victorious'
    UNION ALL SELECT 53034, 'spell_q28813_set_health_random'
    UNION ALL SELECT 96872, 'spell_occuthar_focused_fire'
    UNION ALL SELECT 96931, 'spell_occuthar_eyes_of_occuthar'
    UNION ALL SELECT 96932, 'spell_occuthar_eyes_of_occuthar_vehicle'
    UNION ALL SELECT 96942, 'spell_occuthar_occuthars_destruction'
    UNION ALL SELECT 101009, 'spell_occuthar_occuthars_destruction'
    UNION ALL SELECT 49380, 'spell_trollgore_consume'
    UNION ALL SELECT 59803, 'spell_trollgore_consume'
    UNION ALL SELECT 49555, 'spell_trollgore_corpse_explode'
    UNION ALL SELECT 59807, 'spell_trollgore_corpse_explode'
    UNION ALL SELECT 49405, 'spell_trollgore_invader_taunt'
    UNION ALL SELECT 53242, 'spell_tharon_ja_clear_gift_of_tharon_ja'
    UNION ALL SELECT 63276, 'spell_general_vezax_mark_of_the_faceless'
    UNION ALL SELECT 63278, 'spell_general_vezax_mark_of_the_faceless_leech'
    UNION ALL SELECT 69051, 'spell_devourer_of_souls_mirrored_soul'
    UNION ALL SELECT 69023, 'spell_devourer_of_souls_mirrored_soul_proc'
    UNION ALL SELECT 69048, 'spell_devourer_of_souls_mirrored_soul_target_selector'
) v
LEFT JOIN `spell_script_names` w
  ON w.`spell_id` = v.`spell_id` AND w.`ScriptName` = v.`ScriptName`
WHERE w.`spell_id` IS NULL;

-- Shaman fire elemental pet ScriptName fix
UPDATE `creature_template`
SET `ScriptName` = 'npc_pet_shaman_fire_elemental'
WHERE `entry` = 15438
  AND `ScriptName` <> 'npc_pet_shaman_fire_elemental';
